

spring:
  application:
    name: Platform
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/redtour?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.web.platform.pojo


